services:
  postgres:
    image: postgres:18
    container_name: asa_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  backend:
    build: .
    container_name: asa_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DB_HOST: postgres

volumes:
  postgres_data:
